server:
  address: 127.0.0.1
  port: 8082

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/buber?currentSchema=notification_service
    username: buber
    password: buber
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-timeout: 5000
      idle-timeout: 60000
      validation-timeout: 500
  flyway:
    enabled: true
    default-schema: notification_service
    schemas: notification_service
    create-schemas: true
    locations: classpath:database/migrations

logging:
  level:
    root: INFO
    io.allitov.buber: DEBUG