plugins {
    id 'java'
    alias(libs.plugins.springBootPlugin) apply false
    alias(libs.plugins.springDependencyManagementPlugin) apply false
    alias(libs.plugins.spotlessPlugin) apply false
}

allprojects {
    group = 'io.allitov.buber'
    version = '0.0.1'

    repositories {
        mavenCentral()
    }
}

subprojects {
    apply plugin: 'java'
    apply plugin: 'io.spring.dependency-management'
    apply plugin: 'org.springframework.boot'
    apply plugin: 'com.diffplug.spotless'

    java {
        sourceCompatibility = JavaVersion.VERSION_25
        targetCompatibility = JavaVersion.VERSION_25
    }
    tasks.withType(JavaCompile).configureEach {
        options.encoding = 'UTF-8'
    }

    spotless {
        java {
            target 'src/**/*.java'
            removeUnusedImports()
            trimTrailingWhitespace()
            endWithNewline()
            palantirJavaFormat("2.86.0")
        }
    }

    def installGitHooks = {
        def gitDir = file("${rootDir}/.git")
        if (gitDir.exists()) {
            copy {
                from "${rootDir}/git/hooks"
                into "${gitDir.path}/hooks"
                filePermissions {
                    user { read = true; write = true; execute = true }
                    group { read = true; execute = true }
                    other { read = true; execute = true }
                }
            }
            println "Git hooks installed during project evaluation."
        }
    }
    installGitHooks()

    dependencies {
        implementation libs.lombok
        annotationProcessor libs.lombok
        testImplementation libs.lombok
        testAnnotationProcessor libs.lombok
    }

    test {
        useJUnitPlatform()
    }

    configurations {
        compileOnly {
            extendsFrom annotationProcessor
        }
    }
}