create table if not exists notification_task
(
    id              bigint primary key generated by default as identity,
    trip_id         bigint       not null,
    recipient_type  varchar(20)  not null,
    recipient_id    bigint       not null,
    message         varchar(255) not null,
    status          varchar(20)  not null,
    attempts        integer      not null default 0,
    created_at      timestamptz  not null default now()
);
comment on table notification_task is 'Таблица для хранения задач по уведомлению пользователей.';
comment on column notification_task.id is 'Уникальный идентификатор задачи.';
comment on column notification_task.trip_id is 'Уникальный идентификатор поездки.';
comment on column notification_task.recipient_type is 'Тип получателя (водитель, пассажир).';
comment on column notification_task.recipient_id is 'Уникальный идентификатор получателя.';
comment on column notification_task.message is 'Содержимое уведомления.';
comment on column notification_task.status is 'Состояние выполнения задачи.';
comment on column notification_task.attempts is 'Количество попыток отправки уведомления.';
comment on column notification_task.created_at is 'Время создания задачи.';