create table if not exists passenger
(
    id            bigint primary key generated by default as identity,
    name          varchar(255) not null,
    email         varchar(255),
    phone         varchar(20)  not null unique,
    registered_at timestamptz  not null default now()
);
comment on table passenger is 'Таблица пассажиров.';
comment on column passenger.id is 'Уникальный идентификатор пассажира.';
comment on column passenger.name is 'ФИО пассажира.';
comment on column passenger.email is 'Электронная почта пассажира.';
comment on column passenger.phone is 'Номер телефона пассажира.';
comment on column passenger.registered_at is 'Дата регистрации пассажира.';

------------------------------------------------------------------------------------
create table if not exists driver
(
    id             bigint primary key generated by default as identity,
    name           varchar(255) not null,
    email          varchar(255),
    phone          varchar(20)  not null unique,
    license_number varchar(50)  not null unique,
    status         varchar(20)  not null,
    registered_at  timestamptz  not null default now()
);
comment on table driver is 'Таблица водителей.';
comment on column driver.id is 'Уникальный идентификатор водителя.';
comment on column driver.name is 'ФИО водителя.';
comment on column driver.email is 'Электронная почта водителя.';
comment on column driver.phone is 'Номер телефона водителя.';
comment on column driver.license_number is 'Номер лицензии водителя.';
comment on column driver.status is 'Текущий статус водителя.';
comment on column driver.registered_at is 'Дата регистрации водителя.';
