[versions]
springBootVersion = "4.0.5"
springDependencyManagementVersion = "1.1.7"

[plugins]
springBootPlugin = { id = "org.springframework.boot", version.ref = "springBootVersion" }
springDependencyManagementPlugin = { id = "io.spring.dependency-management", version.ref = "springDependencyManagementVersion" }

[libraries]
