server:
  address: 127.0.0.1
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/buber?currentSchema=user_service
    username: buber
    password: buber
    hikari:
      maximum-pool-size: 10
      minimum-idle: 1
      connection-timeout: 5000
      idle-timeout: 60000
      validation-timeout: 500
  flyway:
    enabled: true
    default-schema: user_service
    schemas: user_service
    create-schemas: true
    locations: classpath:database/migrations
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: user-service-group

logging:
  level:
    root: INFO
    io.allitov.buber: DEBUG

app:
  cache:
    default-ttl: 60m
    config:
      passengers: 30s
      drivers: 30s
  event:
    topic:
      driver-assigned-events: "driver-assigned-events"
      trip-created-events: "trip-created-events"