create table if not exists trip
(
    id           bigint primary key generated by default as identity,
    passenger_id bigint       not null,
    driver_id    bigint,
    status       varchar(20)  not null,
    origin       varchar(255) not null,
    destination  varchar(255) not null,
    price        bigint       not null,
    created_at   timestamptz  not null default now(),
    updated_at   timestamptz  not null default now()
);
comment on table trip is 'Таблица с информацией о поездках.';
comment on column trip.id is 'Уникальный идентификатор записи.';
comment on column trip.passenger_id is 'Уникальный идентификатор пассажира.';
comment on column trip.driver_id is 'Уникальный идентификатор назначенного водителя.';
comment on column trip.status is 'Статус поездки.';
comment on column trip.origin is 'Адрес отправления.';
comment on column trip.destination is 'Адрес назначения.';
comment on column trip.price is 'Стоимость поездки в копейках.';
comment on column trip.created_at is 'Время создания записи.';
comment on column trip.updated_at is 'Время последнего обновления записи.';

create index if not exists idx_trip_passenger_id on trip (passenger_id);
comment on index idx_trip_passenger_id is 'Индекс для быстрого поиска поездок по уникальному идентификатору пассажира.';