openapi: 3.1.0
info:
  title: User Service API
  description: Сервис по управлению пассажирами и водителями.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: локальный сервер
paths:
  /passengers:
    post:
      tags:
        - Пассажиры
      summary: Зарегистрировать пассажира в системе.
      operationId: createPassenger
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PassengerRequest'
      responses:
        201:
          description: Пассажир успешно зарегистрирован.
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    format: int64
                    description: Уникальный идентификатор зарегистрированного пассажира.
        400:
          description: Некорректные значения параметров.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /passengers/{passengerId}:
    get:
      tags:
        - Пассажиры
      summary: Получить информацию о пассажире по уникальному идентификатору.
      operationId: getPassenger
      parameters:
        - name: passengerId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Уникальный идентификатор пассажира.
      responses:
        200:
          description: Информация успешно найдена.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PassengerResponse'
        400:
          description: Некорректные значения параметров.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Информация не найдена.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /drivers:
    post:
      tags:
        - Водители
      summary: Зарегистрировать водителя в системе.
      operationId: createDriver
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DriverRequest'
      responses:
        201:
          description: Водитель успешно зарегистрирован.
          content:
            application/json:
              schema:
                properties:
                  id:
                    type: integer
                    format: int64
                    description: Уникальный идентификатор зарегистрированного водителя.
        400:
          description: Некорректные значения параметров.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /drivers/{driverId}:
    get:
      tags:
        - Водители
      summary: Получить информацию о водителе по уникальному идентификатору.
      operationId: getDriver
      parameters:
        - name: driverId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Уникальный идентификатор водителя.
      responses:
        200:
          description: Информация успешно найдена.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DriverResponse'
        400:
          description: Некорректные значения параметров.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Информация не найдена.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

  /drivers/{driverId}/status:
    patch:
      tags:
        - Водители
      summary: Обновить статус водителя по уникальному идентификатору.
      operationId: updateDriverStatus
      parameters:
        - name: driverId
          in: path
          required: true
          schema:
            type: integer
            format: int64
          description: Уникальный идентификатор водителя.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DriverChangeStatusRequest'
      responses:
        204:
          description: Статус водителя обновлен.
        400:
          description: Некорректные значения параметров.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
        404:
          description: Информация не найдена.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'

components:
  schemas:
    PassengerResponse:
      type: object
      description: Информация о пассажире.
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор пассажира.
        name:
          type: string
          description: ФИО пассажира.
        email:
          type: string
          description: Электронная почта пассажира.
        phone:
          type: string
          description: Номер телефона пассажира.
        registeredAt:
          type: string
          format: date-time
          description: Дата регистрации пассажира.

    PassengerRequest:
      type: object
      required: [name, phone]
      description: Данные о пассажире для регистрации.
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          description: ФИО пассажира.
        email:
          type: string
          minLength: 1
          maxLength: 255
          description: Электронная почта пассажира.
        phone:
          type: string
          minLength: 1
          maxLength: 20
          description: Номер телефона пассажира.

    DriverRequest:
      type: object
      description: Данные о водителе для регистрации.
      required: [name, phone, licenseNumber]
      properties:
        name:
          type: string
          minLength: 1
          maxLength: 255
          description: ФИО водителя.
        email:
          type: string
          minLength: 1
          maxLength: 255
          description: Электронная почта водителя.
        phone:
          type: string
          minLength: 1
          maxLength: 20
          description: Номер телефона водителя.
        licenseNumber:
          type: string
          minLength: 1
          maxLength: 50
          description: Номер лицензии водителя.

    DriverResponse:
      type: object
      description: Информация о водителе.
      properties:
        id:
          type: integer
          format: int64
          description: Уникальный идентификатор водителя.
        name:
          type: string
          description: ФИО водителя.
        email:
          type: string
          description: Электронная почта водителя.
        phone:
          type: string
          description: Номер телефона водителя.
        licenseNumber:
          type: string
          description: Номер лицензии водителя.
        status:
          type: string
          description: Текущий статус водителя.
        registeredAt:
          type: string
          format: date-time
          description: Дата регистрации водителя.

    DriverChangeStatusRequest:
      type: object
      description: Данные о новом статусе водителя.
      required: [status]
      properties:
        status:
          type: string
          enum: [AVAILABLE, BUSY, OFFLINE]
          description: Новый статус водителя.

    Error:
      type: object
      description: Сущность с описанием ошибки.
      properties:
        code:
          type: integer
          format: int32
          description: Код ошибки.
        message:
          type: string
          description: Информация об ошибке.